import { Level, unionBounds } from '../core/level';

// GDScript dla Godot 4.x: LEVELS per warstwa (uzytkownik podpina osobne TileMapLayer),
// wspolne TILES -> atlas coords wg kolejnosci legendy
export function exportGodot(level: Level): string {
  const b = unionBounds(level.layers);
  const levels = level.layers.map((l) => {
    const lines = (b ? l.grid.toLines(b) : []).map((s) => `\t\t${JSON.stringify(s)},`).join('\n');
    return `\t${JSON.stringify(l.name)}: [\n${lines}\n\t],`;
  }).join('\n');
  const tiles = level.legend.entries()
    .map((e, i) => `\t${JSON.stringify(e.ch)}: Vector2i(${i}, 0), # ${e.name}`)
    .join('\n');
  return `# generated by ASCII Level Editor
const LEVELS = {
${levels}
}

const TILES = {
${tiles}
}

func load_layer(tile_map: TileMapLayer, layer_name: String, source_id: int = 0) -> void:
\tvar level = LEVELS[layer_name]
\tfor y in level.size():
\t\tfor x in level[y].length():
\t\t\tvar ch := level[y][x]
\t\t\tif TILES.has(ch):
\t\t\t\ttile_map.set_cell(Vector2i(x, y), source_id, TILES[ch])
`;
}
