import { Level, assertExportableBounds, unionBounds } from '../core/level';

// Godot 4 odrzuca zduplikowane klucze slownika - powtorzone nazwy warstw dostaja
// przyrostek " (2)", " (3)" itd., zeby wygenerowany plik dalej byl poprawny.
// Dedupe po EMITOWANYM kluczu: sufiks bumpujemy TYLKO przy kolizji (nie-kolidujaca
// literalna nazwa np. "x (2)" wychodzi bez zmian). Przy kolizji baza (bez ewentualnego
// literalnego sufiksu " (N)") grupuje ja pod wspolnym licznikiem, ktory bumpuje az do
// unikalnosci - wiec ['dup','dup','dup (2)'] -> ['dup','dup (2)','dup (3)'], a nie 'dup (2) (2)'.
function dedupeKeys(names: string[]): string[] {
  const used = new Set<string>();
  return names.map((name) => {
    if (!used.has(name)) { used.add(name); return name; }
    const base = name.replace(/ \(\d+\)$/, '');
    let n = 2, key = `${base} (${n})`;
    while (used.has(key)) { n++; key = `${base} (${n})`; }
    used.add(key);
    return key;
  });
}

// GDScript dla Godot 4.x: LEVELS per warstwa (uzytkownik podpina osobne TileMapLayer),
// wspolne TILES -> atlas coords wg kolejnosci legendy
export function exportGodot(level: Level): string {
  const b = unionBounds(level.layers);
  assertExportableBounds(b);
  const keys = dedupeKeys(level.layers.map((l) => l.name));
  const levels = level.layers.map((l, i) => {
    const lines = (b ? l.grid.toLines(b) : []).map((s) => `\t\t${JSON.stringify(s)},`).join('\n');
    return `\t${JSON.stringify(keys[i])}: [\n${lines}\n\t],`;
  }).join('\n');
  const tiles = level.legend.entries()
    .map((e, i) => `\t${JSON.stringify(e.ch)}: Vector2i(${i}, 0), # ${e.name}`)
    .join('\n');
  return `# generated by ASCII Level Editor
const LEVELS = {
${levels}
}

const TILES = {
${tiles}
}

func load_layer(tile_map: TileMapLayer, layer_name: String, source_id: int = 0) -> void:
\tvar level = LEVELS[layer_name]
\tfor y in level.size():
\t\tfor x in level[y].length():
\t\t\tvar ch := level[y][x]
\t\t\tif TILES.has(ch):
\t\t\t\ttile_map.set_cell(Vector2i(x, y), source_id, TILES[ch])
`;
}
